services:
  - type: web
    name: remodely-pro
    runtime: node
    plan: starter
    region: oregon
    buildCommand: |
      npm ci
      npx prisma generate
      npm run build:render
    startCommand: npm start
    autoDeploy: false
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: remodely-ai-db
          property: connectionString
      - key: NEXTAUTH_URL
        value: https://remodely.ai
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
    healthCheckPath: /api/health
    domains:
      - remodely.pro
      - www.remodely.pro
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: camera=(), microphone=(), geolocation=()
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"
      - key: PORT
        value: 10000
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false

databases:
  - name: remodely-ai-db
    databaseName: remodely_ai_production
    user: remodely_user
    plan: starter
