services:
  - type: web
    name: remodely-pro
    runtime: node
    plan: starter
    region: oregon
    buildCommand: |
      npm ci
      npx prisma generate
      npm run build
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
    healthCheckPath: /api/health
    domains:
      - remodely.pro
      - www.remodely.pro
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: camera=(), microphone=(), geolocation=()
        value: 572226ab12ee29d87f3c8b1e4a9d6f2e8c5b3a7f1d4e9c2b5a8e1f4d
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: "--max-old-space-size=1024"
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false

databases:
  - name: remodely-ai-db
    plan: starter
