#!/bin/bash

echo "🔍 CSS Selector Update Guide"
echo "============================="
echo ""
echo "1. MANUAL BROWSER INSPECTION (Recommended):"
echo "   • Open the target site in Chrome/Firefox"
echo "   • Right-click on a business listing → 'Inspect Element'"
echo "   • Look for the HTML structure around contractor listings"
echo "   • Note the class names, data attributes, and element structure"
echo "   • Test selectors in browser console: document.querySelectorAll('your-selector')"
echo ""
echo "2. AUTOMATED SELECTOR DISCOVERY:"
echo "   • Run: node discover-selectors.js [website-url]"
echo "   • This script will find common patterns automatically"
echo ""
echo "3. UPDATE SCRAPER FILES:"
echo "   • Edit files in lib/scrapers/"
echo "   • Replace old selectors with new ones"
echo "   • Test with single scraper before updating all"
echo ""
echo "4. TEST UPDATED SCRAPERS:"
echo "   • Run: node test-single-scraper.js [scraper-name]"
echo "   • Verify results before deploying"
echo ""
echo "Let's create tools for each step..."
